-- Autonomous XAUUSD schema for Supabase Postgres
-- Run this file in the Supabase SQL editor when direct SQLAlchemy init
-- is not possible or when you want an explicit SQL migration artifact.

create or replace function public.set_autonomous_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.trade_logs (
  id bigint generated by default as identity primary key,
  broker_ticket varchar(64) not null unique,
  symbol varchar(32) not null,
  timeframe varchar(16) not null,
  side varchar(8) not null,
  mode varchar(16) not null,
  status varchar(16) not null,
  market_regime varchar(32) not null default 'unknown',
  opened_at timestamptz not null,
  closed_at timestamptz,
  entry_price double precision not null,
  exit_price double precision,
  stop_loss double precision not null,
  take_profit double precision not null,
  volume double precision not null,
  pnl double precision,
  rsi double precision,
  rsi_fast double precision,
  ema_fast double precision,
  ema_slow double precision,
  ema_trend double precision,
  atr double precision,
  h4_atr double precision,
  h4_adx double precision,
  d1_trend varchar(8),
  signal_type varchar(32),
  sentiment_score double precision,
  volatility double precision,
  reward_risk_ratio double precision,
  notes text,
  meta jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.model_snapshots (
  id bigint generated by default as identity primary key,
  trained_at timestamptz not null,
  sample_count integer not null,
  accuracy double precision not null,
  precision double precision not null,
  recall double precision not null,
  f1_score double precision not null,
  feature_importances jsonb not null,
  parameter_overrides jsonb not null,
  model_path varchar(512) not null,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.runtime_state (
  key varchar(128) primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create index if not exists trade_logs_broker_ticket_idx on public.trade_logs (broker_ticket);
create index if not exists trade_logs_symbol_idx on public.trade_logs (symbol);
create index if not exists trade_logs_status_idx on public.trade_logs (status);
create index if not exists trade_logs_opened_at_idx on public.trade_logs (opened_at);
create index if not exists model_snapshots_trained_at_idx on public.model_snapshots (trained_at);

drop trigger if exists set_trade_logs_updated_at on public.trade_logs;
create trigger set_trade_logs_updated_at
before update on public.trade_logs
for each row execute function public.set_autonomous_updated_at();

drop trigger if exists set_runtime_state_updated_at on public.runtime_state;
create trigger set_runtime_state_updated_at
before update on public.runtime_state
for each row execute function public.set_autonomous_updated_at();
